### ISSUE TITLE
Arrows are not used

### ISSUE THREAD

**Issue by justbopitharu** [skyarkhangel/CombatRealism#60]
None of the bows actually consume arrows, and as far as i can tell the arrow types don't affect damage or AP ability

**Comment by ProfoundDarkness** [comment]
Unable to reproduce the arrow ammo issue.  I'm using the master branch from git (Dec 30) along with other mods and regularly see the pawns run out of ammo for their bows/great bows.

As a test loaded up just Core and CR release 1.6.9.2, new world (made sure had one pawn that could shoot... ah Rimworld), spawned in some arrows and bows, force pickup (no load out) and did some force firing.

Tested both Bow and Great Bow using all 3 arrow types for each on a drafted colonist.
All bows consumed ammo as expected.

Sounds like maybe you've got another mod in below Combat Realism which overrode the weapon defs from Combat Realism (I've done that a couple of times recently).  I find that Combat Realism is generally best at the bottom of the load order excepting the following:
-Compatibility patches for another mod and Combat Realism (though if those patches are old that could be the issue).
-Miniturization (Due to how it accomplishes what it does, this should work with just about any mod)
-AcEnhanced Stack (Due to how it accomplishes what it does, this should work with just about any mod)

As for damage, well all the arrows look to do the same damage, it's AP that changes.  I don't know enough about AP to tell if that is broken or working for bows/arrows but it seemed to be working on Charged Rifles and the different ammo types there.  I didn't notice a feedback string on the weapons but Charged Rifle loaded with Conc. did a pretty good job vs high armor targets recently.

**Comment by justbopitharu** [comment]
making CR last in load order fixed the issue, not sure what was causing it

**Comment by skyarkhangel** [comment]
Wrong CR load priority
