### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Mythos** [skyarkhangel/CombatRealism#87]
Hey there,

suddenly I got following error message (NullReferenceException) which continuously occurs:

> Exception in RimWorld.ThinkNode_ConditionalCanDoConstantThinkTreeJobNow TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at Combat_Realism.JobGiver_TakeAndEquip.TryGiveJob (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Combat_Realism.Detours_ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
RimWorld.ThinkNode_Conditional:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
Verse.AI.Pawn_JobTracker:DetermineNextConstantThinkTreeJob()
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by ProfoundDarkness** [comment]
If you still have a save from that I wonder, if you zoomed out, if you'd find a prisoner recently freed?  I say this because that looks like #78 to me and the 'suddenly' bit makes me think you marked a prisoner for release and one of your wardens got around to it some time later.

If this is prisoner related there are two things to pass on.
1 - You can avoid this most of the time by keeping weapons in a room other than 'outside' even if the door is always open.  Also helps to finish picking up weapons from raids before releasing the prisoner.
2 - For the most part I've found it's safe to ignore this.  Turn off auto-open on error and if you have it turned on, turn off pause on error.  Remember to restore those settings once the prisoner has left (or has been re-captured) as you could miss out on a more important errors otherwise.

If this wasn't related to a prisoner then I'd bet some additional context would be appreciated.

**Comment by Mythos** [comment]
Hey there, unfortunately it has nothing to do with prisoners. But after
restarting the game it didn't occur so far. If I see that error again, I'll
immediately reply to this issue.

Best regards,
Stefan

ProfoundDarkness <notifications@github.com> schrieb am Sa., 4. Feb. 2017,
20:14:

**Comment by Mythos** [comment]
Unfortunately the error occurred again, but I'm not sure what happened. I just ran the game, no interaction.

> Exception in RimWorld.ThinkNode_ConditionalCanDoConstantThinkTreeJobNow TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at Combat_Realism.JobGiver_TakeAndEquip.TryGiveJob (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Combat_Realism.Detours_ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
RimWorld.ThinkNode_Conditional:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
Verse.AI.Pawn_JobTracker:DetermineNextConstantThinkTreeJob()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()


The weird thing is, that it occurred 7 times (at the same time), so 1 colonist (I have 8) didn't cause that error.
